### ISSUE TITLE
Manually set preferred store

### ISSUE THREAD

**Issue by batbattur** [iFixit/css-gather#13]
## Summary
Sometimes when we run critical-css.yml, the preferred store is set to `DE` instead of `US`. See more at https://github.com/iFixit/ifixit/pull/47892#issuecomment-1550070719.

Let's try manually setting the `US` store by sending `POST` request to `store/user/store_preference` (https://github.com/iFixit/ifixit/pull/47892#issuecomment-1550095750) when we start `penthouse` [here](https://github.com/iFixit/css-gather/blob/799c796af609cd9b9f7227a624440f018acab74e/critical-css.js#L36-L54).

## Background 
https://github.com/iFixit/ifixit/pull/47892#issuecomment-1550070719 and https://github.com/iFixit/ifixit/pull/47892#issuecomment-1550095750

**Comment by mlahargou** [comment]
Has this caused issues recently?

**Comment by batbattur** [comment]
I just checked the screenshots from the last 2-3 weeks' weekly updates and confirmed that all of them have `US` store set.
- https://github.com/iFixit/ifixit/actions/runs/5111641379
- https://github.com/iFixit/ifixit/actions/runs/5045480143
- https://github.com/iFixit/ifixit/actions/runs/4995287765

I think this can be a very low priority or stay in the backlog.
